### ISSUE TITLE
<RuntimeError> when turning trace logging on

### ISSUE THREAD

**Issue by ggayan** [adhearsion/adhearsion#504]
Hey guys,

I have this weird problem as soon as I change the logger level on adhearsion:

`<RuntimeError> can't add a new key into hash during iteration when turning trace logging on`

I thought at first that maybe there was something wrong with an actor that we have for changing dynamically the logger level, but then I tried toggling the logger level using the ALARM signal and the same problem occurred.

The calls don't work for a small amount of time, but then everything seems to work normally without intervention. We discovered that after the event, the app memory usage starts to grow silently until no more threads can be created (it happened this weekend ~20 hours later after the error).

Here is a more complete log:

```
[2014-07-21 13:05:17.187] WARN  Adhearsion::Logging: Turning TRACE logging ON.
[2014-07-21 13:05:18.758] ERROR Adhearsion::OutboundCall: 4ad67b29-7449-4766-bde2-0a7c2d2538c1@: <RuntimeError> can't add a new key into hash during iteration
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/repository.rb:69:in `[]='
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/logger.rb:67:in `block in new'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/logger.rb:51:in `synchronize'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/logger.rb:51:in `new'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/logging.rb:16:in `logger'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/call_controller/dial.rb:186:in `block (2 levels) in prep_calls'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:117:in `call'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:117:in `call_handler'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:96:in `block (3 levels) in trigger_handler'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:91:in `catch'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:91:in `block (2 levels) in trigger_handler'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:89:in `each'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:89:in `find'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:89:in `block in trigger_handler'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:88:in `catch'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:88:in `trigger_handler'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/call.rb:184:in `block in deliver_message'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/foundation/exception_handler.rb:5:in `catching_standard_errors'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/call.rb:183:in `deliver_message'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
[2014-07-21 13:05:20.175] INFO  Adhearsion::OutboundCall: ebc86aa7-e61d-49b2-ab3a-640e074b4dd6@: Call ended due to busy
[2014-07-21 13:05:20.176] INFO  ComparadorPlugin::RequestActor: received ping message
[2014-07-21 13:05:20.177] INFO  Adhearsion::OutboundCall: 9639ac3d-a15c-4d32-acbc-f10ab3822223@: Call ended due to hungup
[2014-07-21 13:05:20.445] ERROR Adhearsion::OutboundCall: 9639ac3d-a15c-4d32-acbc-f10ab3822223@: <RuntimeError> can't add a new key into hash during iteration
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/repository.rb:69:in `[]='
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/logger.rb:67:in `block in new'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/logger.rb:51:in `synchronize'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/logger.rb:51:in `new'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/logging.rb:16:in `logger'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/call_controller/dial.rb:113:in `block in track_originating_call'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:117:in `call'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:117:in `call_handler'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:96:in `block (3 levels) in trigger_handler'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:91:in `catch'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:91:in `block (2 levels) in trigger_handler'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:89:in `each'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:89:in `find'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:89:in `block in trigger_handler'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:88:in `catch'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:88:in `trigger_handler'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/call.rb:184:in `block in deliver_message'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/foundation/exception_handler.rb:5:in `catching_standard_errors'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/call.rb:183:in `deliver_message'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
[2014-07-21 13:05:20.576] INFO  Adhearsion::OutboundCall: 37af895e-0e38-4a9a-ab82-3d069e1f44a0@: Call ended due to reject
[2014-07-21 13:05:20.577] ERROR Adhearsion::OutboundCall: c827292a-7cf0-43b5-8538-3d3e1d3c4af8@: <RuntimeError> can't add a new key into hash during iteration
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/repository.rb:69:in `[]='
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/logger.rb:67:in `block in new'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/logger.rb:51:in `synchronize'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/logger.rb:51:in `new'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/logging.rb:16:in `logger'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/call_controller/dial.rb:322:in `cleanup_calls'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/call_controller/dial.rb:62:in `dial'
	/var/lib/octophone/releases/961d519e391a0c1fabeb3f1add3238bcc7ecb848/app/call/outbound/country_call_controller.rb:58:in `call_client'
	/var/lib/octophone/releases/961d519e391a0c1fabeb3f1add3238bcc7ecb848/app/call/outbound/country_call_controller.rb:24:in `run'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/call_controller.rb:120:in `execute!'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/call_controller.rb:95:in `block in exec'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/call_controller.rb:94:in `catch'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/call_controller.rb:94:in `exec'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/call_controller.rb:111:in `exec_with_callback'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/call_controller.rb:105:in `block (2 levels) in bg_exec'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/foundation/exception_handler.rb:5:in `catching_standard_errors'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/adhearsion-2.5.4/lib/adhearsion/call_controller.rb:104:in `block in bg_exec'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `block in create'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
	/var/lib/octophone/shared/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
[2014-07-21 13:05:20.781] INFO  Adhearsion::CallController::Dial::Dial: c909150c-cc2e-4e19-a976-345da53dd9d5: #dial finished with no remaining outbound calls
```

**Comment by benlangfeld** [comment]
Potentially related to https://github.com/adhearsion/adhearsion/issues/589.

**Comment by ggayan** [comment]
pinging @joaquinrulin as I'm no longer involved with the project :P
