### ISSUE TITLE
Crash on originating outbound call.

### ISSUE THREAD

**Issue by system123** [adhearsion/adhearsion#512]
I upgraded to Adhearsion 2.5.4 and this became an immediate issue. I am originating a call like so:

```ruby
@call = Adhearsion::OutboundCall.new
@call.execute_controller_or_router_on_answer OutboundController, { extension: "1234"}
@call.on_end { |event| account_call(event) }
@call.dial "SIP/1234", from: "0987654321"
```

and I receive the following error

```
[2014-09-07 11:08:09.812] ERROR Celluloid: Actor crashed!
ArgumentError: wrong number of arguments calling `initialize` (0 for 1)
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/adhearsion-2.5.4/lib/adhearsion/call_controller.rb:103:in `bg_exec'
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/adhearsion-2.5.4/lib/adhearsion/call.rb:486:in `execute_controller'
	org/jruby/RubyKernel.java:1945:in `public_send'
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `invoke'
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `task'
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `task'
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `initialize'
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:47:in `initialize'
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `create'
[2014-09-07 11:08:09.813] ERROR Adhearsion::Initializer: <ArgumentError> wrong number of arguments calling `initialize` (0 for 1)
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/adhearsion-2.5.4/lib/adhearsion/call_controller.rb:103:in `bg_exec'
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/adhearsion-2.5.4/lib/adhearsion/call.rb:486:in `execute_controller'
	org/jruby/RubyKernel.java:1945:in `public_send'
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `invoke'
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `task'
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `task'
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `initialize'
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:47:in `initialize'
	/Volumes/Hades/Dropbox/Programming/Teleforge/TFDialer_ahn2/vendor/bundle/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `create'
```

This error is stemming from the fact that Celluloid::ThreadHandler now expects an argument in the intialization:

```ruby
class ThreadHandle
    def initialize(actor_system, role = nil)
      @mutex = Mutex.new
      ....
```

I am not sure what should specified as "actor_system", else I would try patch this myself.

**Comment by benlangfeld** [comment]
Adhearsion 3 uses Celluloid 0.16.
