### ISSUE TITLE
(Seemingly) Random Reel error 

### ISSUE THREAD

**Issue by runningferret** [adhearsion/adhearsion#523]
To preface, I believe this issue is actually a bug deep inside Reel, but since we saw it in our Adhearsion app we felt like it should at least be reported/mentioned here!

We just upgraded Virginia to 0.3.0 and have been happily running ever since. One of our development machines has a load balancer hit it every 15 seconds, which has been totally fine since we upgraded (weeks). Late yesterday afternoon the we didn't see the regular log after 15s, and then Reel crashed:

    192.168.10.8 - - [05/Nov/2014 17:47:22] "GET /status " 200 28 0.0060
    192.168.10.8 - - [05/Nov/2014 17:47:37] "GET /status " 200 28 0.0070
    [2014-11-05 17:48:08] ERROR Celluloid: Reel::Rack::Server crashed!
    Reel::StateError: not in chunked body mode
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-0.5.0/lib/reel/request.rb:94:in `write'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-rack-0.2.0/lib/reel/rack/server.rb:47:in `route_request'
        org/jruby/RubyArray.java:1617:in `each'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/rack-1.4.5/lib/rack/body_proxy.rb:31:in `each'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-rack-0.2.0/lib/reel/rack/server.rb:47:in `route_request'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-rack-0.2.0/lib/reel/rack/server.rb:29:in `on_connection'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-0.5.0/lib/reel/connection.rb:73:in `each_request'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-rack-0.2.0/lib/reel/rack/server.rb:25:in `on_connection'
        org/jruby/RubyMethod.java:134:in `call'
        org/jruby/RubyProc.java:255:in `call'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-0.5.0/lib/reel/server.rb:56:in `handle_connection'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-0.5.0/lib/reel/server.rb:55:in `handle_connection'
        org/jruby/RubyBasicObject.java:1730:in `__send__'
        org/jruby/RubyKernel.java:1932:in `public_send'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `handle_message'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `task'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `initialize'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:47:in `initialize'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `create'
    [2014-11-05 17:48:08] ERROR Adhearsion::Initializer: <Reel::StateError> not in chunked body mode
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-0.5.0/lib/reel/request.rb:94:in `write'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-rack-0.2.0/lib/reel/rack/server.rb:47:in `route_request'
        org/jruby/RubyArray.java:1617:in `each'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/rack-1.4.5/lib/rack/body_proxy.rb:31:in `each'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-rack-0.2.0/lib/reel/rack/server.rb:47:in `route_request'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-rack-0.2.0/lib/reel/rack/server.rb:29:in `on_connection'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-0.5.0/lib/reel/connection.rb:73:in `each_request'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-rack-0.2.0/lib/reel/rack/server.rb:25:in `on_connection'
        org/jruby/RubyMethod.java:134:in `call'
        org/jruby/RubyProc.java:255:in `call'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-0.5.0/lib/reel/server.rb:56:in `handle_connection'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/reel-0.5.0/lib/reel/server.rb:55:in `handle_connection'
        org/jruby/RubyBasicObject.java:1730:in `__send__'
        org/jruby/RubyKernel.java:1932:in `public_send'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `handle_message'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `task'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `initialize'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:47:in `initialize'
        /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `create'
    [2014-11-05 17:48:08] WARN  Celluloid: Terminating task: type=:call, meta={:method_name=>:run}, status=:iowait
    [2014-11-05 17:48:08] INFO  Celluloid: A Reel good HTTP server! (Codename "Bette")
    [2014-11-05 17:48:08] INFO  Celluloid: Listening on http://0.0.0.0:5005

As you can see, the first lines are the regular 15s intervals. The timestamp at the crash is 30 seconds later, hence the one missing log line. Reel restarted right away and continue to serve requests with no issues since, and we do not believe that this would have crashed any calls.

As I mentioned, I'm relatively confident this is an internal Reel bug [based on the code that throws the error.] (https://github.com/celluloid/reel/blob/96c6d00596d6be5f031573eebe93582fd1e9ac9b/lib/reel/request.rb#L9)

This is the first time this has happened, and we strongly suspect that we will likely never see it again, although we did want to officially document it in case anyone else has seen/sees this issue.

**Comment by benlangfeld** [comment]
Closing for inactivity.
