### ISSUE TITLE
Load based issue between Adhearsion 2.4 and 2.5?

### ISSUE THREAD

**Issue by runningferret** [adhearsion/adhearsion#526]
We're experimenting with upgrading to the latest and greatest Adhearsion. Unfortunately, upon running a few load tests we get a few errors that smack of jruby/jruby#999 (we're on JRuby 1.7.4 still, though we've seen similar errors on the latest and greatest JRuby). We're seeing this error crop up under moderate to high call volume:

```
[2014-12-02 15:44:21.538] ERROR Adhearsion::Initializer: <NoMethodError> undefined method `find' for nil:NilClass
    /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:149:in `guarded?'
    /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:92:in `trigger_handler'
    org/jruby/RubyKernel.java:1254:in `catch'
    /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:91:in `trigger_handler'
    org/jruby/RubyEnumerable.java:556:in `find'
    /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:89:in `trigger_handler'
    org/jruby/RubyKernel.java:1254:in `catch'
    /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/has-guarded-handlers-1.6.0/lib/has_guarded_handlers.rb:88:in `trigger_handler'
    /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/punchblock-2.5.3/lib/punchblock/translator/asterisk/call.rb:159:in `process_ami_event'
    /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/punchblock-2.5.3/lib/punchblock/translator/asterisk.rb:209:in `ami_dispatch_to_or_create_call'
    org/jruby/RubyHash.java:1357:in `each_pair'
    /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/punchblock-2.5.3/lib/punchblock/translator/asterisk.rb:207:in `ami_dispatch_to_or_create_call'
    /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/punchblock-2.5.3/lib/punchblock/translator/asterisk.rb:90:in `handle_ami_event'
    org/jruby/RubyKernel.java:1932:in `public_send'
    /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
    /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
    /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `handle_message'
    /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `task'
    /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `initialize'
    /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:47:in `initialize'
    /srv/phone/apptastic/shared/bundle/jruby/1.9/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `create'
```

I am working on the assumption that nobody is in fact passing in `nil` as an array of guards :) While it's entirely possible that this is entirely in `has-guarded-handlers`, as that bumped from 1.5 to 1.6 when we did the upgrade, we suspect it is the interaction between the handlers and Adhearsion/Punchlock. 

We're able to somewhat reliably reproduce this just by running a SIPp test under somewhat heavy load, so I'm confident if we're able to ferret out a cause and fix I can confirm it is cleaned up.

Have you guys seen anything like this before, or have any ideas on where to dig in next? We've combed around in has-guarded-handlers but haven't seen anything that jumps out at us.

**Comment by Jared-Prime** [comment]
see also https://github.com/cloudvox/apptastic/issues/354 for more issues with observed "slowness" between 2.4 and 2.5/6
