### ISSUE TITLE
say/speak is broken for freeswitch mod_flite

### ISSUE THREAD

**Issue by gregory** [adhearsion/adhearsion#542]
in freeswitch: 
`2015-02-23 08:16:09.925641 [ERR] mod_flite.c:100 Valid voice names are awb, rms, slt or kal.``

my call in ahn: `say "Rub dub dub, three men in a tub.", tts_voice: 'kal'``

"logs": 

```bash
[2015-02-23 08:16:10.003] ERROR Adhearsion::Call: 0c984afa-c052-4eb7-afe6-3317e88df097@localhost: <Adhearsion::CallController::Output::PlaybackError> Output failed due to #<Adhearsi
on::Error: : #<Punchblock::Component::Output target_call_id="0c984afa-c052-4eb7-afe6-3317e88df097", target_mixer_name=nil, component_id="output-1", source_uri="xmpp:0c984afa-c052-4e
b7-afe6-3317e88df097@localhost/output-1", domain="localhost", transport=nil, timestamp=Mon, 23 Feb 2015 08:16:09 +0000, request_id="b45e89b1-3c07-431f-adf2-373f557efed0", headers={}
, voice=nil, interrupt_on=nil, start_offset=nil, start_paused=nil, repeat_interval=nil, repeat_times=nil, max_time=nil, renderer="flite", render_documents=[#<Punchblock::Component::
Output::Document target_call_id=nil, target_mixer_name=nil, component_id=nil, source_uri=nil, domain=nil, transport=nil, timestamp=Mon, 23 Feb 2015 08:16:09 +0000, url=nil, content_
type="application/ssml+xml", value=<speak xmlns="http://www.w3.org/2001/10/synthesis" version="1.0" xml:lang="en-US">Rub dub dub, three men in a tub.</speak>>]>>
        /usr/local/lib/ruby/gems/2.0.0/gems/adhearsion-2.6.0/lib/adhearsion/call_controller/output/player.rb:23:in `rescue in output'
        /usr/local/lib/ruby/gems/2.0.0/gems/adhearsion-2.6.0/lib/adhearsion/call_controller/output/player.rb:13:in `output'
```

I wish i could contribute if i knew where that was, but couldn't find anything about that neither in the doc neither by grepping.

**Comment by benlangfeld** [comment]
Please provide full logs, at trace level from adhearsion and debug level from FreeSWITCH.

**Comment by benlangfeld** [comment]
Also, notice that the voice in the command you set is nil. The correct command would be `say "Rub dub dub, three men in a tub.", voice: 'kal'`. Where did you get `tts_voice` from?
