### ISSUE TITLE
Sending a prompt component with a bad grammar `value` causes call to hang

### ISSUE THREAD

**Issue by bklang** [adhearsion/adhearsion#562]
Logs: https://gist.github.com/bklang/eaeaf8aeaa6e465a5311

> Ben Langfeld [11:05 AM] 
> So first up, your prompt component is bad: https://gist.github.com/bklang/eaeaf8aeaa6e465a5311#file-gistfile1-txt-L104
> 
> Ben Klang [11:05 AM] 
how?
> 
> Ben Langfeld [11:05 AM] 
> `value="http://10.203.175.51:8080/grammars/corporate_ivr/employee_names", content_type="application/srgs+xml", url=nil`
> 
> Ben Langfeld [11:05 AM]
> value and url should be swapped

Adhearsion should fail gracefully (and not hang the call) if the grammar value is incorrect

**Comment by benlangfeld** [comment]
Log after the above change:

```
15:04:50 ahn.1  | [2016-01-06 15:04:50.696] DEBUG Adhearsion::Call: @: Receiving message: #<Adhearsion::Event::Offer target_call_id="3e5664c4-a75a-48c6-9df0-01ed293352aa", target_mixer_name=nil, component_id=nil, source_uri=nil, domain=nil, transport=nil, timestamp=Wed, 06 Jan 2016 15:04:50 -0200, headers={"X-agi_request"=>"async", "X-agi_channel"=>"SIP/192.168.0.15-00000008", "X-agi_language"=>"en", "X-agi_type"=>"SIP", "X-agi_uniqueid"=>"1452099883.8", "X-agi_version"=>"11.7.0~dfsg-1ubuntu1", "X-agi_callerid"=>"unknown", "X-agi_calleridname"=>"unknown", "X-agi_callingpres"=>"0", "X-agi_callingani2"=>"0", "X-agi_callington"=>"0", "X-agi_callingtns"=>"0", "X-agi_dnid"=>"1", "X-agi_rdnis"=>"unknown", "X-agi_context"=>"default", "X-agi_extension"=>"1", "X-agi_priority"=>"1", "X-agi_enhanced"=>"0.0", "X-agi_accountcode"=>"", "X-agi_threadid"=>"139909857400576"}, to="1", from="unknown <SIP/unknown>">
15:04:50 ahn.1  | [2016-01-06 15:04:50.705] INFO  Adhearsion::Router: Call 3e5664c4-a75a-48c6-9df0-01ed293352aa selected route "test" (#<Proc:0x27eb679c@/Users/ben/code/phrg/talkbox/config/adhearsion.rb:39>)
15:04:50 ahn.1  | [2016-01-06 15:04:50.716] DEBUG Adhearsion::Call: 3e5664c4-a75a-48c6-9df0-01ed293352aa@: Executing command #<Adhearsion::Rayo::Command::Accept target_call_id=nil, target_mixer_name=nil, component_id=nil, source_uri=nil, domain=nil, transport=nil, timestamp=Wed, 06 Jan 2016 15:04:50 -0200, request_id="2bffaf45-b561-4ee9-ba68-124f34246e33", headers={}>
15:04:50 ahn.1  | [2016-01-06 15:04:50.777] INFO  Adhearsion::Call: 3e5664c4-a75a-48c6-9df0-01ed293352aa@: Executing controller Adhearsion::CallController
15:04:50 ahn.1  | [2016-01-06 15:04:50.781] DEBUG Adhearsion::Call: 3e5664c4-a75a-48c6-9df0-01ed293352aa@: Receiving message: #<Adhearsion::Event::Offer target_call_id="3e5664c4-a75a-48c6-9df0-01ed293352aa", target_mixer_name=nil, component_id=nil, source_uri=nil, domain=nil, transport=nil, timestamp=Wed, 06 Jan 2016 15:04:50 -0200, headers={"X-agi_request"=>"async", "X-agi_channel"=>"SIP/192.168.0.15-00000008", "X-agi_language"=>"en", "X-agi_type"=>"SIP", "X-agi_uniqueid"=>"1452099883.8", "X-agi_version"=>"11.7.0~dfsg-1ubuntu1", "X-agi_callerid"=>"unknown", "X-agi_calleridname"=>"unknown", "X-agi_callingpres"=>"0", "X-agi_callingani2"=>"0", "X-agi_callington"=>"0", "X-agi_callingtns"=>"0", "X-agi_dnid"=>"1", "X-agi_rdnis"=>"unknown", "X-agi_context"=>"default", "X-agi_extension"=>"1", "X-agi_priority"=>"1", "X-agi_enhanced"=>"0.0", "X-agi_accountcode"=>"", "X-agi_threadid"=>"139909857400576"}, to="1", from="unknown <SIP/unknown>">
15:04:50 ahn.1  | [2016-01-06 15:04:50.840] DEBUG Adhearsion::Call: 3e5664c4-a75a-48c6-9df0-01ed293352aa@: Executing command #<Adhearsion::Rayo::Component::Prompt target_call_id=nil, target_mixer_name=nil, component_id=nil, source_uri=nil, domain=nil, transport=nil, timestamp=Wed, 06 Jan 2016 15:04:50 -0200, request_id="daa31ff6-87eb-4186-bc23-7460be3ddc47", barge_in=true, output=#<Adhearsion::Rayo::Component::Output target_call_id=nil, target_mixer_name=nil, component_id=nil, source_uri=nil, domain=nil, transport=nil, timestamp=Wed, 06 Jan 2016 15:04:50 -0200, request_id="ae612086-ffcb-4418-a526-c56452ae2d4c", headers={}, voice=nil, interrupt_on=nil, start_offset=nil, start_paused=nil, repeat_interval=nil, repeat_times=nil, max_time=nil, renderer="unimrcp", render_documents=[#<Adhearsion::Rayo::Component::Output::Document target_call_id=nil, target_mixer_name=nil, component_id=nil, source_uri=nil, domain=nil, transport=nil, timestamp=Wed, 06 Jan 2016 15:04:50 -0200, url=nil, content_type="application/ssml+xml", value=<speak version="1.0" xml:lang="en-US" xmlns="http://www.w3.org/2001/10/synthesis">Foo bar?</speak>>]>, input=#<Adhearsion::Rayo::Component::Input target_call_id=nil, target_mixer_name=nil, component_id=nil, source_uri=nil, domain=nil, transport=nil, timestamp=Wed, 06 Jan 2016 15:04:50 -0200, request_id="c9a56b9c-0a62-438b-af22-3a99cd2de78b", headers={}, max_silence=5000, min_confidence=0.5, mode=:dtmf, recognizer="unimrcp", language="en-US", terminator=nil, sensitivity=nil, initial_timeout=5000, inter_digit_timeout=2000, recognition_timeout=nil, grammars=[#<Adhearsion::Rayo::Component::Input::Grammar target_call_id=nil, target_mixer_name=nil, component_id=nil, source_uri=nil, domain=nil, transport=nil, timestamp=Wed, 06 Jan 2016 15:04:50 -0200, value="http://foo.com/bar.baz", content_type="application/srgs+xml", url=nil>]>>
15:04:50 ahn.1  | [2016-01-06 15:04:50.847] ERROR Adhearsion::Translator::Asterisk::Component::MRCPPrompt: Call ID: 3e5664c4-a75a-48c6-9df0-01ed293352aa, Component ID: 4e7a2f77-e584-4f37-9d03-7703d34b15a0: <NoMethodError> undefined method `to_doc' for "http://foo.com/bar.baz":String
15:04:50 ahn.1  | 	/Users/ben/code/adhearsion/lib/adhearsion/translator/asterisk/component/mrcp_recog_prompt.rb:123:in `block in grammars'
15:04:50 ahn.1  | 	org/jruby/RubyArray.java:2300:in `map'
15:04:50 ahn.1  | 	/Users/ben/code/adhearsion/lib/adhearsion/translator/asterisk/component/mrcp_recog_prompt.rb:121:in `grammars'
15:04:50 ahn.1  | 	/Users/ben/code/adhearsion/lib/adhearsion/translator/asterisk/component/mrcp_recog_prompt.rb:58:in `validate'
15:04:50 ahn.1  | 	/Users/ben/code/adhearsion/lib/adhearsion/translator/asterisk/component/mrcp_prompt.rb:29:in `validate'
15:04:50 ahn.1  | 	/Users/ben/code/adhearsion/lib/adhearsion/translator/asterisk/component/mrcp_recog_prompt.rb:25:in `execute'
15:04:50 ahn.1  | 	/Users/ben/code/adhearsion/lib/adhearsion/translator/asterisk/call.rb:375:in `block in execute_component'
15:04:50 ahn.1  | 	org/jruby/RubyKernel.java:1755:in `tap'
15:04:50 ahn.1  | 	/Users/ben/code/adhearsion/lib/adhearsion/translator/asterisk/call.rb:373:in `execute_component'
15:04:50 ahn.1  | 	/Users/ben/code/adhearsion/lib/adhearsion/translator/asterisk/call.rb:285:in `execute_command'
15:04:50 ahn.1  | 	/Users/ben/code/adhearsion/lib/adhearsion/translator/asterisk.rb:125:in `execute_call_command'
15:04:50 ahn.1  | 	/Users/ben/code/adhearsion/lib/adhearsion/translator/asterisk.rb:114:in `execute_command'
15:04:50 ahn.1  | 	org/jruby/RubyKernel.java:1824:in `public_send'
15:04:50 ahn.1  | 	/usr/local/Cellar/rbenv/0.4.0/versions/jruby-9.0.4.0/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
15:04:50 ahn.1  | 	/usr/local/Cellar/rbenv/0.4.0/versions/jruby-9.0.4.0/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
15:04:50 ahn.1  | 	/usr/local/Cellar/rbenv/0.4.0/versions/jruby-9.0.4.0/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
15:04:50 ahn.1  | 	/usr/local/Cellar/rbenv/0.4.0/versions/jruby-9.0.4.0/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
15:04:50 ahn.1  | 	/usr/local/Cellar/rbenv/0.4.0/versions/jruby-9.0.4.0/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
15:04:50 ahn.1  | 	/usr/local/Cellar/rbenv/0.4.0/versions/jruby-9.0.4.0/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
15:04:50 ahn.1  | 	/usr/local/Cellar/rbenv/0.4.0/versions/jruby-9.0.4.0/lib/ruby/gems/shared/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
15:04:50 ahn.1  | [2016-01-06 15:04:50.853] DEBUG Adhearsion::Call: 3e5664c4-a75a-48c6-9df0-01ed293352aa@: Finished executing controller #<Adhearsion::CallController call=3e5664c4-a75a-48c6-9df0-01ed293352aa, metadata={}>
15:04:50 ahn.1  | [2016-01-06 15:04:50.853] ERROR Adhearsion::Call: 3e5664c4-a75a-48c6-9df0-01ed293352aa@: <Adhearsion::ProtocolError> #<Adhearsion::ProtocolError: name="option error" text="The requested grammars could not be parsed." call_id=nil component_id=nil>
15:04:50 ahn.1  | [2016-01-06 15:04:50.856] INFO  Adhearsion::Router::Route: Call 3e5664c4-a75a-48c6-9df0-01ed293352aa routing completed. Hanging up now.
15:04:50 ahn.1  | [2016-01-06 15:04:50.857] INFO  Adhearsion::Call: 3e5664c4-a75a-48c6-9df0-01ed293352aa@: Hanging up
15:04:50 ahn.1  | [2016-01-06 15:04:50.860] DEBUG Adhearsion::Call: 3e5664c4-a75a-48c6-9df0-01ed293352aa@: Executing command #<Adhearsion::Rayo::Command::Hangup target_call_id=nil, target_mixer_name=nil, component_id=nil, source_uri=nil, domain=nil, transport=nil, timestamp=Wed, 06 Jan 2016 15:04:50 -0200, request_id="a349fb36-b31f-4ef8-9200-9c98dc3241e5", headers={}>
15:04:50 ahn.1  | [2016-01-06 15:04:50.905] DEBUG Adhearsion::Call: 3e5664c4-a75a-48c6-9df0-01ed293352aa@: Receiving message: #<Adhearsion::Event::Answered target_call_id="3e5664c4-a75a-48c6-9df0-01ed293352aa", target_mixer_name=nil, component_id=nil, source_uri=nil, domain=nil, transport=nil, timestamp=Wed, 06 Jan 2016 17:04:43 +0000, headers={}>
15:04:50 ahn.1  | [2016-01-06 15:04:50.911] DEBUG Adhearsion::Call: 3e5664c4-a75a-48c6-9df0-01ed293352aa@: Receiving message: #<Adhearsion::Event::Complete target_call_id="3e5664c4-a75a-48c6-9df0-01ed293352aa", target_mixer_name=nil, component_id="4e7a2f77-e584-4f37-9d03-7703d34b15a0", source_uri="4e7a2f77-e584-4f37-9d03-7703d34b15a0", domain=nil, transport=nil, timestamp=Wed, 06 Jan 2016 15:04:50 -0200, reason=#<Adhearsion::Event::Complete::Hangup target_call_id=nil, target_mixer_name=nil, component_id=nil, source_uri=nil, domain=nil, transport=nil, timestamp=Wed, 06 Jan 2016 15:04:50 -0200, name=:hangup>, recording=nil, fax=nil, fax_metadata={}>
15:04:50 ahn.1  | [2016-01-06 15:04:50.914] DEBUG Adhearsion::Call: 3e5664c4-a75a-48c6-9df0-01ed293352aa@: Receiving message: #<Adhearsion::Event::End target_call_id="3e5664c4-a75a-48c6-9df0-01ed293352aa", target_mixer_name=nil, component_id=nil, source_uri=nil, domain=nil, transport=nil, timestamp=Wed, 06 Jan 2016 17:04:43 +0000, headers={}, reason=:hungup, platform_code="16">
15:04:50 ahn.1  | [2016-01-06 15:04:50.914] ERROR Adhearsion::Call: 3e5664c4-a75a-48c6-9df0-01ed293352aa@: <Adhearsion::ProtocolError> #<Adhearsion::ProtocolError: name="option error" text="The requested grammars could not be parsed." call_id=nil component_id=nil>
15:04:52 ahn.1  | [2016-01-06 15:04:50.915] INFO  Adhearsion::Call: 3e5664c4-a75a-48c6-9df0-01ed293352aa@: Call unknown <SIP/unknown> -> 1 ended due to hungup (code 16)
```
